### ISSUE TITLE
Phatcrack API fails to start on first run

### ISSUE THREAD

**Issue by JSmith-Aura** [lachlan2k/phatcrack#11]
When using the provided docker compose, phatcrack as a whole fails to properly start (with the main frontend getting 502 due to api initialisation failure).

This may occur due to postgres taking some time to initialise the first time. We could try and do a reconnect in the API on failure.

**Comment by lachlan2k** [comment]
Fixed in https://github.com/lachlan2k/phatcrack/commit/03debd9dfa4ce1d4192cc778e3906366b875be21

**Comment by JSmith-Aura** [comment]
Truly a lord and a scholar
