### ISSUE TITLE
Error Handling is Unclear on the Frontend

### ISSUE THREAD

**Issue by JSmith-Aura** [lachlan2k/phatcrack#22]
Howdy, 

When entering in a hashlist with a name that is 4 characters or below, e.g "flop" an error is generated:

```json
{
    "message": "Key: 'HashlistCreateRequestDTO.Name' Error:Field validation for 'Name' failed on the 'min' tag"
}
```

This is fine, however it isnt clearly communicated to the front end:

![image](https://github.com/lachlan2k/phatcrack/assets/98988287/b5761f5a-7433-4e8f-af4a-99f54eb09d4d)

Which makes it a little hard to diagnose whats wrong. 

Version: `v0.1.0`

Thanks!

**Comment by lachlan2k** [comment]
Error handling for the Wizard steps has been moved to the new toast error handlers now in commit 10866334d6725f21bec78141474bc952be50d999.

However I will leave this issue open with the following TODOs before we can finally close it:

- [ ] Ensure the new toast error handling is used for all API requests, so errors are more obvious
- [ ] Ensure the UI enforces all the same constraints as the backend, so these errors don't happen in the first place.
- [ ] Write a custom error message format that is more friendly than what go-playground/validator gives us. For example, something like "'Name' needs to be a minimum of 4 characters" would be far better.
