### ISSUE TITLE
MFA

### ISSUE THREAD

**Issue by lachlan2k** [lachlan2k/phatcrack#3]
- [x] Implement MFA with WebAuthN/U2F
- [x] Add configuration option to require users to configure MFA on first login

**Comment by NHAS** [comment]
This has been completed right?

**Comment by lachlan2k** [comment]
In theory, yes. I'd like one day to also offer TOTP for those who wish to delpoy with that option, but for now, as WebAuthN has been implemented.

For now, this issue can be closed.
