### ISSUE TITLE
Randomly generate password on user creation

### ISSUE THREAD

**Issue by JSmith-Aura** [lachlan2k/phatcrack#30]
Howdy chief, 
In the "create user" dialog it'd be quite neat if a randomly generated password was automatically generated for you so all you had to do was hit "create".

![image](https://github.com/lachlan2k/phatcrack/assets/98988287/aae1fc13-3438-4dfd-9a6a-a6d7b6dd1389)

This could also be coupled with a check box with "force password change on login"

**Comment by lachlan2k** [comment]
Sounds good, I'll add it.

I'd imagine this would also be quite useful when using the API to provision accounts/

**Comment by JSmith-Aura** [comment]
Yeah definitely. 

(love your work and you)

**Comment by lachlan2k** [comment]
donezo
