### ISSUE TITLE
Agent crash on missing mask

### ISSUE THREAD

**Issue by JSmith-Aura** [lachlan2k/phatcrack#39]
Howdy, got a bug where an agent will crash if mask attack is specified but no mask is given:

```
2024/04/30 17:54:04 Received: DeleteFileRequest
2024/05/01 15:50:53 Received: JobStart
2024/05/01 15:50:53 unrecoverable handler error: error when handling message: using mask attack (3), but no mask was given
```

**Comment by lachlan2k** [comment]
The error is now non-fatal as of (some time ago). It let's the user create the attack, but the attack instantly exits and gives the user an error.

Ideally this should be validated at submission time, rather then starting the attack. But, that can come later.
