### ISSUE TITLE
Job Templates

### ISSUE THREAD

**Issue by lachlan2k** [lachlan2k/phatcrack#6]
Users should be able eto create job templates. I.e. "this wordlist + this rules" or "this mask attack".

Even better if they can be done in a batch. For example, if I can click a handful of buttons, chuck in some NTLM hashes, and I'm off to the races cracking with 3 different techniques, that would be amazing.

This can likely be mostly frontend-driven. API endpoints can be used to serve up preconfigured `hashcat_params`, which the frontend can then apply to the wizard, etc.

**Comment by TheraNinjaCat** [comment]
Has there been any progress on this feature? It seems similar to #41. Another potential improvement could be supporting multiple masks or a maskfile as a single attack, which would allow, in effect, queuing multiple mask jobs into a single job.

**Comment by lachlan2k** [comment]
Currently I'm working on a more generic file upload mechanism, so as well as uploading wordlists, rules, etc. you'll be able to upload maskfiles, which should hopefully help alleviate this and #16 .

After that, I'll be implementing #17 and then after that I'll be looking at templates :)

**Comment by lachlan2k** [comment]
Implemented in 942e7a0c7b3bda5e8e01134251a50dcc51d19913 :)
